# Generated by Django 6.1.1 on 2026-10-07 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_budget', models.PositiveIntegerField()),
                ('headcount_target', models.PositiveIntegerField()),
                ('strategic_goals', models.TextField(blank=True, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='departments.department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_leave_allowance', models.PositiveIntegerField(default=20)),
                ('sick_leave_days', models.PositiveIntegerField(blank=True, null=True)),
                ('bonus_eligibility', models.BooleanField(default=False)),
                ('manager_review', models.TextField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_budget', models.IntegerField()),
                ('milestones', models.TextField(blank=True, null=True)),
                ('targets', models.TextField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Not-Started', 'Not-Started'), ('Ongoing', 'Ongoing'), ('On-hold', 'On-hold'), ('Cancelled', 'Cancelled')], default='Not-Started', max_length=20)),
                ('completion_percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
