# Generated by Django 6.1.1 on 2026-10-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentrecords',
            options={'verbose_name_plural': 'Department Records'},
        ),
        migrations.AlterModelOptions(
            name='employeerecords',
            options={'verbose_name_plural': 'Employee Records'},
        ),
        migrations.AlterModelOptions(
            name='projectrecords',
            options={'verbose_name_plural': 'Project Records'},
        ),
    ]
